turbine:
  aggregator:
    clusterConfig: MYAPP2
  appConfig: MYAPP2,MYAPP
test:
  app:
    name: config server default app
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true    
