eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
    probes:
      enabled: true
  endpoints:
    web:
      exposure:
        include: actuator,health,info
  endpoint:
    health:
      enabled: true

    info:
      enabled: true
