eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: actuator,health,info
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
